name: Build Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
      
    - name: Lint
      run: npm run lint
      working-directory: ./frontend
      
    - name: Build
      run: npm run build
      working-directory: ./frontend 
      
    - name: Check for changes in Addresses.ts
      run: |
        git fetch origin main:main
        if git diff --name-only origin/main...HEAD | grep -q 'frontend/src/api/Addresses.ts'; then
          echo "::error::Changes in Addresses.ts are not allowed."
          exit 1
        fi
