name: Check Addresses.ts for Changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for changes in Addresses.ts
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'frontend/src/api/Addresses.ts'; then
            echo "::error::Changes in Addresses.ts are not allowed."
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          
      - name: Fail if changes detected
        if: env.CHANGED == 'true'
        run: exit 1
