name: Check Addresses.ts for Changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for changes in Addresses.ts
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'frontend/src/api/Addresses.ts')
          if [ ! -z "$CHANGES" ]; then
            echo "Changes in Addresses.ts are not allowed."
            exit 1
          fi

