name: Check Addresses.ts for Changes

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'frontend/src/api/Addresses.ts'

jobs:
  check-addresses-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for changes in Addresses.ts
      run: |
        git fetch origin main:main
        if git diff --name-only origin/main...HEAD | grep -q 'frontend/src/api/Addresses.ts'; then
          echo "::error::Changes in Addresses.ts are not allowed."
          exit 1
        fi
