name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-materials:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore AcademicHub.Common dependencies
      run: dotnet restore ./AcademicHub.Common/AcademicHub.Common.sln
      
    - name: Build AcademicHub.Common
      run: dotnet build ./AcademicHub.Common/AcademicHub.Common.sln --no-restore
      
    - name: Restore Materials dependencies
      run: dotnet restore ./Materials/Materials.sln

    - name: Build Materials
      run: dotnet build ./Materials/Materials.sln --no-restore  
      
    # Calculate code coverage percentage for unit tests

    - name: Calculate unit test coverage
      run: |
        dotnet test ./Materials/Materials.UnitTests/Materials.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./Materials/Materials.UnitTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_unit" -ne 60 ]; then
          echo "Error: Code coverage for unit tests is not 60%."
          exit 1
        fi
      shell: bash
      
      # Calculate code coverage percentage for integration tests
    - name: Calculate integration test coverage
      run: |
        dotnet test ./Materials/Materials.IntegrationTests/Materials.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./Materials/Materials.IntegrationTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_integration" -ne 60 ]; then
          echo "Error: Code coverage for integration tests is not 60%."
          exit 1
        fi
      shell: bash