name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-identity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./Identity/Identity.sln

    - name: Build
      run: dotnet build ./Identity/Identity.sln --no-restore

    # Calculate code coverage percentage for unit tests

    - name: Calculate unit test coverage
      run: |
        dotnet test ./Identity/Identity.UnitTests/Identity.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./Identity/Identity.UnitTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_unit" -ne 60 ]; then
          echo "Error: Code coverage for unit tests is not 60%."
          exit 1
        fi
      shell: bash
      
      # Calculate code coverage percentage for integration tests
    - name: Calculate integration test coverage
      run: |
        dotnet test ./Identity/Identity.IntegrationTests/Identity.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./Identity/Identity.IntegrationTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_integration" -ne 60 ]; then
          echo "Error: Code coverage for integration tests is not 60%."
          exit 1
        fi
      shell: bash