name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-courseStream:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore CustomExceptions dependencies
      run: dotnet restore ./AcademicHub.Common/AcademicHub.Common.sln
      
    - name: Build CustomExceptions
      run: dotnet build ./AcademicHub.Common/AcademicHub.Common.sln --no-restore
      
    - name: Restore CourseStream dependencies
      run: dotnet restore ./CourseStream/CourseStream.sln

    - name: Build CourseStream
      run: dotnet build ./CourseStream/CourseStream.sln --no-restore

      # Calculate code coverage percentage for unit tests
    - name: Calculate unit test coverage
      run: |
        dotnet test ./CourseStream/CourseStream.UnitTests/CourseStream.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./CourseStream/CourseStream.UnitTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_unit" -ne 100 ]; then
          echo "Error: Code coverage for unit tests is not 100%."
          exit 1
        fi
      shell: bash
      
      # Calculate code coverage percentage for integration tests
    - name: Calculate integration test coverage
      run: |
        dotnet test ./CourseStream/CourseStream.IntegrationTests/CourseStream.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./CourseStream/CourseStream.IntegrationTests/coverage.opencover.xml -X gcov)

        if [ "$coverage_percentage_integration" -ne 100 ]; then
          echo "Error: Code coverage for integration tests is not 100%."
          exit 1
        fi
      shell: bash