version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: materials-postgres-container
    environment:
      - POSTGRESQL_DATABASE=Materials
      - POSTGRESQL_USER=materialsuser
      - POSTGRESQL_PASSWORD=materialsuser
    ports:
      - "5439:5432"
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge